### ISSUE TITLE
Failed to list *v1.Package: invalid character '\x00' in string literal

### ISSUE THREAD

**Issue by JannikZed** [fission/fission#1148]
The fission executor suddenly writes the following error (once per second):
```
E0403 11:50:26.576813       1 reflector.go:205] github.com/fission/fission/executor/poolmgr/gpm.go:125: Failed to list *v1.Package: invalid character '\x00' in string literal
E0403 11:50:27.591522       1 reflector.go:205] github.com/fission/fission/executor/poolmgr/gpm.go:125: Failed to list *v1.Package: invalid character '\x00' in string literal
E0403 11:50:28.609411       1 reflector.go:205] github.com/fission/fission/executor/poolmgr/gpm.go:125: Failed to list *v1.Package: invalid character '\x00' in string literal
E0403 11:50:29.623241       1 reflector.go:205] github.com/fission/fission/executor/poolmgr/gpm.go:125: Failed to list *v1.Package: invalid character '\x00' in string literal
E0403 11:50:30.637824       1 reflector.go:205] github.com/fission/fission/executor/poolmgr/gpm.go:125: Failed to list *v1.Package: invalid character '\x00' in string literal
E0403 11:50:31.656439       1 reflector.go:205] github.com/fission/fission/executor/poolmgr/gpm.go:125: Failed to list *v1.Package: invalid character '\x00' in string literal
E0403 11:50:32.673721       1 reflector.go:205] github.com/fission/fission/executor/poolmgr/gpm.go:125: Failed to list *v1.Package: invalid character '\x00' in string literal
E0403 11:50:33.692831       1 reflector.go:205] github.com/fission/fission/executor/poolmgr/gpm.go:125: Failed to list *v1.Package: invalid character '\x00' in string literal
E0403 11:50:34.714517       1 reflector.go:205] github.com/fission/fission/executor/poolmgr/gpm.go:125: Failed to list *v1.Package: invalid character '\x00' in string literal
E0403 11:50:35.740442       1 reflector.go:205] github.com/fission/fission/executor/poolmgr/gpm.go:125: Failed to list *v1.Package: invalid character '\x00' in string literal
E0403 11:50:36.757937       1 reflector.go:205] github.com/fission/fission/executor/poolmgr/gpm.go:125: Failed to list *v1.Package: invalid character '\x00' in string literal
E0403 11:50:37.774163       1 reflector.go:205] github.com/fission/fission/executor/poolmgr/gpm.go:125: Failed to list *v1.Package: invalid character '\x00' in string literal
E0403 11:50:38.788668       1 reflector.go:205] github.com/fission/fission/executor/poolmgr/gpm.go:125: Failed to list *v1.Package: invalid character '\x00' in string literal
``` 
I was already trying to remove all functions and environments and try to create them all from scratch. Furthermore, I deleted all controll and exectution pods to let them get newly created, again. Creating a new environment is working. When trying to apply a function spec with environment and package I get the following error:
``` 
fission spec apply --wait
Fatal error: Failed to apply specs: Internal error -
``` 

fission controller log: 
```
{"level":"info","ts":1554292371.8564806,"logger":"controller.api","caller":"fission/common.go:86","msg":"handled","host":"127.0.0.1","method":"GET","uri":"/v2/packages?namespace=","proto":"HTTP/1.1","status_code":500,"size":1}
goroutine 4808 [running]:
runtime/debug.Stack(0xea1770, 0xc420023380, 0xc420627678)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/fission/fission/controller.(*API).respondWithError(0xc4202cdf80, 0x7fcadb535430, 0xc420364e40, 0x16c6e20, 0xc420704510)
	/go/src/github.com/fission/fission/controller/api.go:113 +0x37
github.com/fission/fission/controller.(*API).PackageApiList(0xc4202cdf80, 0x7fcadb535430, 0xc420364e40, 0xc4202cef00)
	/go/src/github.com/fission/fission/controller/packageApi.go:40 +0x26d
github.com/fission/fission/controller.(*API).PackageApiList-fm(0x7fcadb535430, 0xc420364e40, 0xc4202cef00)
	/go/src/github.com/fission/fission/controller/api.go:202 +0x48
net/http.HandlerFunc.ServeHTTP(0xc420086dc0, 0x7fcadb535430, 0xc420364e40, 0xc4202cef00)
	/usr/local/go/src/net/http/server.go:1947 +0x44
github.com/fission/fission/vendor/github.com/gorilla/handlers.loggingHandler.ServeHTTP(0x16c7a20, 0xc4200c4008, 0x16c90c0, 0xc420086dc0, 0xc420674240, 0x16e1180, 0xc42039c460, 0xc4202cef00)
	/go/src/github.com/fission/fission/vendor/github.com/gorilla/handlers/logging.go:45 +0x133
github.com/fission/fission.LoggingMiddleware.func1.1(0x16e1180, 0xc42039c460, 0xc4202cef00)
	/go/src/github.com/fission/fission/common.go:94 +0x168
net/http.HandlerFunc.ServeHTTP(0xc420642260, 0x16e1180, 0xc42039c460, 0xc4202cef00)
	/usr/local/go/src/net/http/server.go:1947 +0x44
github.com/fission/fission/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc42031fc80, 0x16e1180, 0xc42039c460, 0xc42066b100)
	/go/src/github.com/fission/fission/vendor/github.com/gorilla/mux/mux.go:212 +0xcd
net/http.serverHandler.ServeHTTP(0xc4200ba270, 0x16e1180, 0xc42039c460, 0xc42066b100)
	/usr/local/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc4205ceaa0, 0x16e2fc0, 0xc4202e46c0)
	/usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2795 +0x27b
{"level":"info","ts":1554292409.526945,"logger":"controller.api","caller":"fission/common.go:86","msg":"handled","host":"127.0.0.1","method":"GET","uri":"/v2/packages?namespace=","proto":"HTTP/1.1","status_code":500,"size":1}
```

**Comment by life1347** [comment]
@JannikZed Thanks for the report! We definitely a better way to handle such errors.
 
As a workaround, you can use
```
fission pkg list
fission pkg delete --name <pkg name>
```
If it still not works for you, try
```
kubectl -n default get packages 
kubectl -n default delete packages <pkg name>
```

**Comment by JannikZed** [comment]
which one is the package that makes the issues? I can't find it out ..
```
kubectl -n default get packages
Error from server: invalid character '\x00' in string literal
``` 
I'm getting this error already when using the kubectl

**Comment by JannikZed** [comment]
ok, by manually deleting pkg by pkg I found the one, that made the problems. I still don't know why ..
It's working now again.

**Comment by life1347** [comment]
I met the same problem when implementing `fission support` (see [here](https://github.com/fission/fission/blob/913888a29d4d5ef8164649b148d50535cbad1255/fission/support/resources/resource.go#L47-L51)), but it first time for me see this problem in executor. For unknown reason, sometimes the return objects from kubernetes contain empty bytes in json body and break `json.Marshel`. 
The solution at that time is to remove empty which is not a good idea when creating user's package. 
I'm thinking to give alert to user or at least print logs for such cases but not deceide yet.  Please let me know if you have any suggestion. And thanks again for the report.

**Comment by JannikZed** [comment]
For me it happened for only one specific package - that means, kubernetes always returned empty bytes for this certain package? Really strange .. 
I don't have any other suggestion on how to fix this issue for others. This github issue itself will help googling it ;)

**Comment by life1347** [comment]
@JannikZed do you know the kubernetes version?

**Comment by JannikZed** [comment]
sure: 
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:10Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by soamvasani** [comment]
Is there some fission bug while writing the package, or validation that we need to add?  Do we even know which field of the CRD has the invalid char?

**Comment by life1347** [comment]
Close. Reopen if we have more clues.
