### ISSUE TITLE
"Precondition failed: UID in precondition" when updating package

### ISSUE THREAD

**Issue by life1347** [fission/fission#1380]
**Fission/Kubernetes version**

<pre>
master branch
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**

GKE

**Describe the bug**

```
/go/src/pkg/buildermgr/pkgwatcher.go:177
2019-11-05T06:16:23.156Z	ERROR	builder_manager.package_watcher	buildermgr/common.go:145	error updating package	{"error": "Operation cannot be fulfilled on packages.fission.io \"java-src-pkg-zip-16c7\": StorageError: invalid object, Code: 4, Key: /registry/fission.io/packages/default/java-src-pkg-zip-16c7, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: a6dd447c-ff93-11e9-9337-42010a800108, UID in object meta: "}
github.com/fission/fission/pkg/buildermgr.updatePackage
	/go/src/pkg/buildermgr/common.go:145
github.com/fission/fission/pkg/buildermgr.(*packageWatcher).build
	/go/src/pkg/buildermgr/pkgwatcher.go:178
```

Looks like its related to https://github.com/kubernetes/kubernetes/issues/82130

**Comment by alexec** [comment]
```
controller | E0522 03:33:44.298546   15107 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
 controller | goroutine 278 [running]:
 controller | k8s.io/apimachinery/pkg/util/runtime.logPanic(0x16a5340, 0x272e0f0)
 controller | 	/home/circleci/.go_workspace/pkg/mod/k8s.io/apimachinery@v0.16.7-beta.0/pkg/util/runtime/runtime.go:74 +0xa3
 controller | k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
 controller | 	/home/circleci/.go_workspace/pkg/mod/k8s.io/apimachinery@v0.16.7-beta.0/pkg/util/runtime/runtime.go:48 +0x82
 controller | panic(0x16a5340, 0x272e0f0)
 controller | 	/home/circleci/sdk/go1.13.4/src/runtime/panic.go:679 +0x1b2
 controller | github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).deletePDBResource(0xc000458240, 0x18a4526, 0x9)
 controller | 	/home/circleci/.go_workspace/src/github.com/argoproj/argo/workflow/controller/operator.go:2643 +0x41
 controller | github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).markWorkflowPhase(0xc000458240, 0x18a121f, 0x5, 0x1, 0xc000bad938, 0x1, 0x1)
 controller | 	/home/circleci/.go_workspace/src/github.com/argoproj/argo/workflow/controller/operator.go:1643 +0x639
 controller | github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).markWorkflowError(0xc000458240, 0x1ae1480, 0xc000559f10, 0x1)
 controller | 	/home/circleci/.go_workspace/src/github.com/argoproj/argo/workflow/controller/operator.go:1681 +0x99
 controller | github.com/argoproj/argo/workflow/controller.(*WorkflowController).processNextItem(0xc00035ce00, 0xc0005a1e00)
 controller | 	/home/circleci/.go_workspace/src/github.com/argoproj/argo/workflow/controller/controller.go:433 +0xfd7
 controller | github.com/argoproj/argo/workflow/controller.(*WorkflowController).runWorker(0xc00035ce00)
 controller | 	/home/circleci/.go_workspace/src/github.com/argoproj/argo/workflow/controller/controller.go:364 +0x2b
 controller | k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000ad6410)
 controller | 	/home/circleci/.go_workspace/pkg/mod/k8s.io/apimachinery@v0.16.7-beta.0/pkg/util/wait/wait.go:152 +0x5e
 controller | k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000ad6410, 0x3b9aca00, 0x0, 0x1, 0xc000049860)
 controller | 	/home/circleci/.go_workspace/pkg/mod/k8s.io/apimachinery@v0.16.7-beta.0/pkg/util/wait/wait.go:153 +0xf8
 controller | k8s.io/apimachinery/pkg/util/wait.Until(0xc000ad6410, 0x3b9aca00, 0xc000049860)
 controller | 	/home/circleci/.go_workspace/pkg/mod/k8s.io/apimachinery@v0.16.7-beta.0/pkg/util/wait/wait.go:88 +0x4d
 controller | created by github.com/argoproj/argo/workflow/controller.(*WorkflowController).Run
 controller | 	/home/circleci/.go_workspace/src/github.com/argoproj/argo/workflow/controller/controller.go:177 +0x9cd
 controller | panic: runtime error: invalid memory address or nil pointer dereference [recovered]
 controller | 	panic: runtime error: invalid memory address or nil pointer dereference
```

Unrelated?

**Comment by adolsalamanca** [comment]
I'm experiencing the very same error trying to deploy a very simple app that connects to a Postgres database and does a test query to it.

I've followed [package](https://fission.io/docs/usage/function/package/) instructions for this.

**Comment by soharab-ic** [comment]
@adolsalamanca I am not able to reproduce this issue.
Please try these steps:
- Try latest fission version `v1.20.2` or master branch of fission.
- Try these source [files](https://github.com/fission/examples/tree/main/python/sourcepkg) when following [package](https://fission.io/docs/usage/function/package/) instructions as file contents in the instructions are incomplete.
