### ISSUE TITLE
Keda MQT broken by exist kafka MQT

### ISSUE THREAD

**Issue by chenjr0719** [fission/fission#1889]
When I upgrade Fission and enable Keda MQT, the mqtrigger-keda cannot start properly because of those already existed Kafka MQT. Those Kafka MQT missing some required fields so the mqtrigger-keda can not works normally. 

The error logs:
```
{"level":"error","ts":"2020-12-16T07:12:13.201Z","caller":"mqtrigger/scalermanager.go:105","msg":"Failed to create ScaledObject","error":"ScaledObject.keda.k8s.io \"kafka-mqttest\" is invalid: [spec.maxReplicaCount: Invalid value: \"null\": spec.maxReplicaCount in body must be of type integer: \"null\", spec.minReplicaCount: Invalid value: \"null\": spec.minReplicaCount in body must be of type integer: \"null\", spec.pollingInterval: Invalid value: \"null\": spec.pollingInterval in body must be of type integer: \"null\", spec.triggers.metadata: Invalid value: \"null\": spec.triggers.metadata in body must be of type object: \"null\", spec.cooldownPeriod: Invalid value: \"null\": spec.cooldownPeriod in body must be of type integer: \"null\"]"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1224cfe]
goroutine 292 [running]:
github.com/fission/fission/pkg/mqtrigger.checkAndUpdateTriggerFields(0xc0002e6bd8, 0xc0002e6bd8, 0xc0008ddc80)
	/go/src/pkg/mqtrigger/scalermanager.go:244 +0x23e
github.com/fission/fission/pkg/mqtrigger.StartScalerManager.func2.1(0x1bd5d20, 0xc0002e6bd8, 0x1bd5d20, 0xc0002e6bd8, 0xc0002e2360, 0xc0003523c0, 0xc000105970, 0x7fff66f216f3, 0x15)
	/go/src/pkg/mqtrigger/scalermanager.go:121 +0x79
created by github.com/fission/fission/pkg/mqtrigger.StartScalerManager.func2
	/go/src/pkg/mqtrigger/scalermanager.go:118 +0x91
```

**Comment by sanketsudake** [comment]
This issue might not be relevant now.

@chenjr0719 Closing issue for now. Feel free to reopen if you are still facing issue.
