### ISSUE TITLE
Executor crashes in v1.14.0 for newdeploy functions

### ISSUE THREAD

**Issue by munjalpatel** [fission/fission#2140]
**Fission/Kubernetes version**

<pre>
$ fission --version
client:
  fission/core:
    BuildDate: "2021-08-02T11:44:22Z"
    GitCommit: f4702fe066c48e05cd5c093311fe95e4a6a971a4
    Version: 1.14.0
server:
  fission/core:
    BuildDate: "2021-08-02T09:30:56Z"
    GitCommit: f4702fe066c48e05cd5c093311fe95e4a6a971a4
    Version: 1.14.0

$ kubectl version

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-13+d2965f0db10712", GitCommit:"d2965f0db1071203c6f5bc662c2827c71fc8b20d", GitTreeState:"clean", BuildDate:"2021-06-26T00:59:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
</pre>

**Kubernetes platform**
AWS EKS

**Describe the bug**
After upgrading to Fission v1.14.0, when I do `fission spec apply --specdir ./specs.tmp --delete true --wait true` the `executor` pod starts crashing.

**To Reproduce**

1. Create a golang env
```sh
fission env create \
  --spec \
  --name go \
  --poolsize 1 \
  --image fission/go-env-1.13 \
  --builder fission/go-builder-1.13 \
  --mincpu 20 \
  --maxcpu 100 \
  --minmemory 16 \
  --maxmemory 64 \
  --version 3 \
  --envns k-system \
  --labels "app=go-env"
```

2. Create a python env
```sh
fission env create \
  --spec \
  --name python \
  --image fission/python-env \
  --builder fission/python-builder \
  --mincpu 10 \
  --maxcpu 100 \
  --minmemory 32 \
  --maxmemory 128 \
  --version 3 \
  --envns k-system \
  --labels "app=python-env"
```

3. Create a function in golang and its route
```sh
fission fn create \
  --spec \
  --name crypto \
  --env go \
  --envns k-system \
  --fns k-system \
  --mincpu 20 \
  --maxcpu 100 \
  --minmemory 16 \
  --maxmemory 64 \
  --minscale 1 \
  --maxscale 5 \
  --targetcpu 90 \
  --src "actions/crypto/*" \
  --entrypoint Handler \
  --executortype newdeploy \
  --concurrency 5 \
  --requestsperpod 10 \
  --secret "action-crypto" \
  --labels "app=crypto,version=0.1.0"
```

```sh
fission httptrigger create \
  --spec \
  --name crypto \
  --function crypto \
  --fns k-system \
  --method POST \
  --url /k-system/crypto/{operation}
```
4. Create a function in python and its route
```sh
fission fn create \
  --spec \
  --name email \
  --env python \
  --envns k-system \
  --fns k-system \
  --src "actions/email/*" \
  --entrypoint main.handler \
  --executortype poolmgr \
  --concurrency 5 \
  --requestsperpod 10 \
  --secret "action-email" \
  --labels "app=email,version=0.1.0"
```

```sh
fission httptrigger create \
  --spec \
  --name email \
  --function email \
  --fns k-system \
  --method POST \
  --url /k-system/email
```
5. Deploy envs, fns and routes
```sh
fission spec apply --specdir ./specs.tmp --delete true --wait true
```

**Expected result**
Environments and functions should get deployed without any errors.

**Actual result**
- Only builder pods for golang and python gets created.
- Fission Executor pod starts crashing with the following errors:

```
2021-08-03T01:22:52.953Z	INFO	executor/executor.go:276	Starting executor	{"instanceID": "tzjh6otc"}
2021-08-03T01:22:52.959Z	INFO	CaaF	container/containermgr.go:314	CaaF starts to clean orphaned resources	{"instanceID": "tzjh6otc"}
2021-08-03T01:22:52.959Z	INFO	generic_pool_manager	poolmgr/gpm.go:421	Poolmanager starts to clean orphaned resources	{"instanceID": "tzjh6otc"}
2021-08-03T01:22:52.960Z	INFO	new_deploy	newdeploy/newdeploymgr.go:330	Newdeploy starts to clean orphaned resources	{"instanceID": "tzjh6otc"}
2021-08-03T01:22:53.000Z	DEBUG	cms/cmscontroller.go:47	Creating ConfigMap & Secret Controller
2021-08-03T01:22:53.001Z	INFO	executor	executor/api.go:255	starting executor API	{"port": 8888}
2021-08-03T01:22:53.018Z	DEBUG	new_deploy	newdeploy/funchandlers.go:33	create deployment for function	{"fn": {"name":"email","namespace":"k-system-fix-email-secrets","uid":"906e093c-4f35-4d9f-88ad-3af30866427f","resourceVersion":"3430284","generation":2,"creationTimestamp":"2021-08-03T01:04:45Z","annotations":{"fission-name":"k-system-fix-email-secrets","fission-uid":"a3b18325-d92f-4272-9a76-4097ea286381"},"managedFields":[{"manager":"fission-bundle","operation":"Update","apiVersion":"fission.io/v1","time":"2021-08-03T01:04:45Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:fission-name":{},"f:fission-uid":{}}},"f:spec":{".":{},"f:InvokeStrategy":{".":{},"f:ExecutionStrategy":{".":{},"f:ExecutorType":{},"f:MaxScale":{},"f:MinScale":{},"f:SpecializationTimeout":{},"f:TargetCPUPercent":{}},"f:StrategyType":{}},"f:concurrency":{},"f:environment":{".":{},"f:name":{},"f:namespace":{}},"f:functionTimeout":{},"f:idletimeout":{},"f:package":{".":{},"f:functionName":{},"f:packageref":{".":{},"f:name":{},"f:namespace":{},"f:resourceversion":{}}},"f:requestsPerPod":{},"f:resources":{},"f:secrets":{}}}}]}, "fnspec": {"environment":{"namespace":"k-system-fix-email-secrets","name":"python"},"package":{"packageref":{"namespace":"k-system-fix-email-secrets","name":"email-e602302a-c748-4ad0-a561-89f1c8734e07","resourceversion":"3429982"},"functionName":"main.handler"},"secrets":[{"namespace":"k-system-fix-email-secrets","name":"action-email"}],"resources":{},"InvokeStrategy":{"ExecutionStrategy":{"ExecutorType":"poolmgr","MinScale":0,"MaxScale":0,"TargetCPUPercent":0,"SpecializationTimeout":120},"StrategyType":"execution"},"functionTimeout":60,"idletimeout":120,"concurrency":5,"requestsPerPod":10}}
2021-08-03T01:22:53.033Z	DEBUG	new_deploy	newdeploy/funchandlers.go:40	end create deployment for function	{"fn": {"name":"email","namespace":"k-system-fix-email-secrets","uid":"906e093c-4f35-4d9f-88ad-3af30866427f","resourceVersion":"3430284","generation":2,"creationTimestamp":"2021-08-03T01:04:45Z","annotations":{"fission-name":"k-system-fix-email-secrets","fission-uid":"a3b18325-d92f-4272-9a76-4097ea286381"},"managedFields":[{"manager":"fission-bundle","operation":"Update","apiVersion":"fission.io/v1","time":"2021-08-03T01:04:45Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:fission-name":{},"f:fission-uid":{}}},"f:spec":{".":{},"f:InvokeStrategy":{".":{},"f:ExecutionStrategy":{".":{},"f:ExecutorType":{},"f:MaxScale":{},"f:MinScale":{},"f:SpecializationTimeout":{},"f:TargetCPUPercent":{}},"f:StrategyType":{}},"f:concurrency":{},"f:environment":{".":{},"f:name":{},"f:namespace":{}},"f:functionTimeout":{},"f:idletimeout":{},"f:package":{".":{},"f:functionName":{},"f:packageref":{".":{},"f:name":{},"f:namespace":{},"f:resourceversion":{}}},"f:requestsPerPod":{},"f:resources":{},"f:secrets":{}}}}]}, "fnspec": {"environment":{"namespace":"k-system-fix-email-secrets","name":"python"},"package":{"packageref":{"namespace":"k-system-fix-email-secrets","name":"email-e602302a-c748-4ad0-a561-89f1c8734e07","resourceversion":"3429982"},"functionName":"main.handler"},"secrets":[{"namespace":"k-system-fix-email-secrets","name":"action-email"}],"resources":{},"InvokeStrategy":{"ExecutionStrategy":{"ExecutorType":"poolmgr","MinScale":0,"MaxScale":0,"TargetCPUPercent":0,"SpecializationTimeout":120},"StrategyType":"execution"},"functionTimeout":60,"idletimeout":120,"concurrency":5,"requestsPerPod":10}}
2021-08-03T01:22:53.023Z	DEBUG	new_deploy	newdeploy/funchandlers.go:33	create deployment for function	{"fn": {"name":"crypto","namespace":"k-system-fix-email-secrets","uid":"0dd34a20-aea4-451e-80c3-a2526924e434","resourceVersion":"3430297","generation":2,"creationTimestamp":"2021-08-03T01:04:44Z","annotations":{"fission-name":"k-system-fix-email-secrets","fission-uid":"a3b18325-d92f-4272-9a76-4097ea286381"},"managedFields":[{"manager":"fission-bundle","operation":"Update","apiVersion":"fission.io/v1","time":"2021-08-03T01:04:44Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:fission-name":{},"f:fission-uid":{}}},"f:spec":{".":{},"f:InvokeStrategy":{".":{},"f:ExecutionStrategy":{".":{},"f:ExecutorType":{},"f:MaxScale":{},"f:MinScale":{},"f:SpecializationTimeout":{},"f:TargetCPUPercent":{}},"f:StrategyType":{}},"f:concurrency":{},"f:environment":{".":{},"f:name":{},"f:namespace":{}},"f:functionTimeout":{},"f:idletimeout":{},"f:package":{".":{},"f:functionName":{},"f:packageref":{".":{},"f:name":{},"f:namespace":{},"f:resourceversion":{}}},"f:requestsPerPod":{},"f:resources":{".":{},"f:limits":{".":{},"f:cpu":{},"f:memory":{}},"f:requests":{".":{},"f:cpu":{},"f:memory":{}}},"f:secrets":{}}}}]}, "fnspec": {"environment":{"namespace":"k-system-fix-email-secrets","name":"go"},"package":{"packageref":{"namespace":"k-system-fix-email-secrets","name":"crypto-c8447f73-d32d-45bd-aa4d-56095f8c1599","resourceversion":"3429974"},"functionName":"Handler"},"secrets":[{"namespace":"k-system-fix-email-secrets","name":"action-crypto"}],"resources":{"limits":{"cpu":"100m","memory":"64Mi"},"requests":{"cpu":"20m","memory":"16Mi"}},"InvokeStrategy":{"ExecutionStrategy":{"ExecutorType":"newdeploy","MinScale":1,"MaxScale":5,"TargetCPUPercent":90,"SpecializationTimeout":120},"StrategyType":"execution"},"functionTimeout":60,"idletimeout":120,"concurrency":5,"requestsPerPod":10}}
2021-08-03T01:22:53.072Z	DEBUG	generic_pool_manager	utils/rbacutils.go:254	service account already present in rolebinding so nothing to add	{"service_account_name": "fission-fetcher", "service_account_namespace": "k-system-fix-email-secrets", "role_binding": "secret-configmap-getter-binding", "role_binding_namespace": "k-system-fix-email-secrets"}
2021-08-03T01:22:53.072Z	DEBUG	generic_pool_manager	poolmgr/funchandlers.go:72	successfully set up rolebinding for fetcher service account for function	{"service_account": "fission-fetcher", "service_account_namepsace": "k-system-fix-email-secrets", "function_name": "email", "function_namespace": "k-system-fix-email-secrets"}
2021-08-03T01:22:53.073Z	INFO	generic_pool_manager.generic_pool	poolmgr/gp.go:111	creating pool	{"environment": {"name":"go","namespace":"k-system-fix-email-secrets","uid":"44aeddc5-b67f-44ce-b5b5-37d6e519a01a","resourceVersion":"3429955","generation":1,"creationTimestamp":"2021-08-03T01:04:44Z","labels":{"app":"go-env","version":""},"annotations":{"fission-name":"k-system-fix-email-secrets","fission-uid":"a3b18325-d92f-4272-9a76-4097ea286381"},"managedFields":[{"manager":"fission-bundle","operation":"Update","apiVersion":"fission.io/v1","time":"2021-08-03T01:04:44Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:fission-name":{},"f:fission-uid":{}},"f:labels":{".":{},"f:app":{},"f:version":{}}},"f:spec":{".":{},"f:builder":{".":{},"f:command":{},"f:image":{}},"f:imagepullsecret":{},"f:keeparchive":{},"f:poolsize":{},"f:resources":{".":{},"f:limits":{".":{},"f:cpu":{},"f:memory":{}},"f:requests":{".":{},"f:cpu":{},"f:memory":{}}},"f:runtime":{".":{},"f:image":{}},"f:version":{}}}}]}}
panic: runtime error: slice bounds out of range [:17] with length 6

goroutine 178 [running]:
github.com/fission/fission/pkg/executor/executortype/newdeploy.(*NewDeploy).getObjName(0xc0005f8460, 0xc00048ed80, 0xc000056060, 0xc0009b518a)
	/go/src/github.com/fission/fission/pkg/executor/executortype/newdeploy/newdeploymgr.go:727 +0x20f
github.com/fission/fission/pkg/executor/executortype/newdeploy.(*NewDeploy).fnCreate(0xc0005f8460, 0xc00048ed80, 0xc000ac99e0, 0xc000941b38, 0x1becd01)
	/go/src/github.com/fission/fission/pkg/executor/executortype/newdeploy/newdeploymgr.go:427 +0x15a
github.com/fission/fission/pkg/executor/executortype/newdeploy.(*NewDeploy).createFunction.func1(0xc000ac9901, 0xc000941b38, 0xc000ac99e0, 0xc000af4f00, 0xc000941c00)
	/go/src/github.com/fission/fission/pkg/executor/executortype/newdeploy/newdeploymgr.go:379 +0x45
github.com/fission/fission/pkg/throttler.(*Throttler).RunOnce(0xc0009027e0, 0xc0008c7800, 0x24, 0xc000941bd8, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/fission/fission/pkg/throttler/throttler.go:215 +0x158
github.com/fission/fission/pkg/executor/executortype/newdeploy.(*NewDeploy).createFunction(0xc0005f8460, 0xc00048ed80, 0x1e, 0xc00098ef80, 0x2)
	/go/src/github.com/fission/fission/pkg/executor/executortype/newdeploy/newdeploymgr.go:377 +0xe5
github.com/fission/fission/pkg/executor/executortype/newdeploy.(*NewDeploy).FunctionEventHandlers.func1.1(0x211e1e0, 0xc00048ed80, 0xc0005f8460)
	/go/src/github.com/fission/fission/pkg/executor/executortype/newdeploy/funchandlers.go:34 +0x234
created by github.com/fission/fission/pkg/executor/executortype/newdeploy.(*NewDeploy).FunctionEventHandlers.func1
	/go/src/github.com/fission/fission/pkg/executor/executortype/newdeploy/funchandlers.go:31 +0x52
```

**Comment by sanketsudake** [comment]
@munjalpatel Could you please verify with 1.14.1 if your issue is resolved ?

**Comment by munjalpatel** [comment]
@sanketsudake 1.14.1 fixes it. Thanks a lot for a quick turnaround on this :)
