### ISSUE TITLE
Kafka MQTrigger causes NewTicker errors

### ISSUE THREAD

**Issue by vishal-biyani** [fission/fission#2211]
A lot of uses are reporting an issue with Kafka MQTrigger (Kind - fission). It may be related to https://github.com/Shopify/sarama/issues/1638 but it is not 100% clear at this point in time.

```
{"level":"info","ts":"2021-09-28T16:01:37.922Z","logger":"kafka","caller":"mqtrigger/mqtmanager.go:172","msg":"created a new consumer","brokers":["fission-test-kafka-brokers:9092"],"input topic":"input","output topic":"output","error topic":"error","trigger name":"kafkatest","function namespace":"default","function name":"consumerfunc"}
{"level":"info","ts":"2021-09-28T16:01:37.943Z","logger":"kafka","caller":"mqtrigger/mqtmanager.go:172","msg":"created a new producer","brokers":["fission-test-kafka-brokers:9092"],"input topic":"input","output topic":"output","error topic":"error","trigger name":"kafkatest","function namespace":"default","function name":"consumerfunc"}
{"level":"info","ts":"2021-09-28T16:01:37.943Z","logger":"message_queue_trigger_manager","caller":"runtime/asm_amd64.s:1371","msg":"message queue trigger created","trigger_name":"kafkatest"}
{"level":"info","ts":"2021-09-28T16:01:38.026Z","logger":"kafka","caller":"runtime/asm_amd64.s:1371","msg":"consumer notification","notification":{"Type":1,"Claimed":null,"Released":null,"Current":{}}}
panic: non-positive interval for NewTicker

goroutine 121 [running]:
time.NewTicker(0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.8/libexec/src/time/tick.go:24 +0x151
github.com/bsm/sarama-cluster.(*Consumer).cmLoop(0xc0000d60f0, 0xc0008cfc20)
	/Users/sanket/go/pkg/mod/github.com/bsm/sarama-cluster@v2.1.15+incompatible/consumer.go:452 +0x5a
github.com/bsm/sarama-cluster.(*loopTomb).Go.func1(0xc0008f79c0, 0xc00086c7a0)
	/Users/sanket/go/pkg/mod/github.com/bsm/sarama-cluster@v2.1.15+incompatible/util.go:73 +0x7b
created by github.com/bsm/sarama-cluster.(*loopTomb).Go
	/Users/sanket/go/pkg/mod/github.com/bsm/sarama-cluster@v2.1.15+incompatible/util.go:69 +0x66
```

**Comment by vishal-biyani** [comment]
This is duplicate of https://github.com/fission/fission/issues/2209 hence closing
