### ISSUE TITLE
Router crashloop infinite with  segmentation violation code 1.16.0-rc1

### ISSUE THREAD

**Issue by info2000** [fission/fission#2366]
```
Fission version 1.16.0-rc1
kubernetes v1.22.2

```

**Kubernetes platform: baremetal servers 3 masters, 3 workers **

Router pods start a CrashLoopBackOff cascade stopping the cluster for long time
![image](https://user-images.githubusercontent.com/5422722/154802946-0f3b7afc-4549-4fdc-86b7-8b3f0a7a3b53.png)

The log output on all the pods is like this

```
{"level":"error","ts":"2022-02-19T13:27:43.709Z","logger":"triggerset.http_trigger_set.dsync","caller":"httputil/reverseproxy.go:295","msg":"error sending request to function","trace_id":"ff47d0f7fa100d0857daf61b8d5f7939","error":"Unable to get service url for connection","errorVerbose":"Unable to get service url for connection\ngithub.com/fission/fission/pkg/router.(*RetryingRoundTripper).RoundTrip\n\tpkg/router/functionHandler.go:411\nnet/http/httputil.(*ReverseProxy).ServeHTTP\n\t/usr/local/Cellar/go@1.16/1.16.13/libexec/src/net/http/httputil/reverseproxy.go:293\ngithub.com/fission/fission/pkg/router.functionHandler.handler\n\tpkg/router/functionHandler.go:529\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/Cellar/go@1.16/1.16.13/libexec/src/net/http/server.go:2050\ngo.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP\n\t/Users/sanket/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.26.0/handler.go:179\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/Users/sanket/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210\ngithub.com/fission/fission/pkg/router.(*mutableRouter).ServeHTTP\n\tpkg/router/mutablemux.go:52\ngo.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP\n\t/Users/sanket/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.26.0/handler.go:179\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/Cellar/go@1.16/1.16.13/libexec/src/net/http/server.go:2868\nnet/http.(*conn).serve\n\t/usr/local/Cellar/go@1.16/1.16.13/libexec/src/net/http/server.go:1933\nruntime.goexit\n\t/usr/local/Cellar/go@1.16/1.16.13/libexec/src/runtime/asm_amd64.s:1371","function":{"apiVersion":"fission.io/v1","kind":"Function","namespace":"default","name":"dsync2022-7"},"status":"Internal Server Error","code":500,"stacktrace":"net/http/httputil.(*ReverseProxy).ServeHTTP\n\t/usr/local/Cellar/go@1.16/1.16.13/libexec/src/net/http/httputil/reverseproxy.go:295\ngithub.com/fission/fission/pkg/router.functionHandler.handler\n\tpkg/router/functionHandler.go:529\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/Cellar/go@1.16/1.16.13/libexec/src/net/http/server.go:2050\ngo.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP\n\t/Users/sanket/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.26.0/handler.go:179\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/Users/sanket/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210\ngithub.com/fission/fission/pkg/router.(*mutableRouter).ServeHTTP\n\tpkg/router/mutablemux.go:52\ngo.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP\n\t/Users/sanket/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.26.0/handler.go:179\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/Cellar/go@1.16/1.16.13/libexec/src/net/http/server.go:2868\nnet/http.(*conn).serve\n\t/usr/local/Cellar/go@1.16/1.16.13/libexec/src/net/http/server.go:1933"}
{"level":"error","ts":"2022-02-19T13:27:43.709Z","logger":"triggerset.http_trigger_set.dsync.roundtripper","caller":"httputil/reverseproxy.go:293","msg":"Unable to get service url for connection","trace_id":"cdbb08e2d23b058e125e45035b66b570","function":"dsync2022-7","namespace":"default","stacktrace":"net/http/httputil.(*ReverseProxy).ServeHTTP\n\t/usr/local/Cellar/go@1.16/1.16.13/libexec/src/net/http/httputil/reverseproxy.go:293\ngithub.com/fission/fission/pkg/router.functionHandler.handler\n\tpkg/router/functionHandler.go:529\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/Cellar/go@1.16/1.16.13/libexec/src/net/http/server.go:2050\ngo.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP\n\t/Users/sanket/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.26.0/handler.go:179\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/Users/sanket/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210\ngithub.com/fission/fission/pkg/router.(*mutableRouter).ServeHTTP\n\tpkg/router/mutablemux.go:52\ngo.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP\n\t/Users/sanket/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.26.0/handler.go:179\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/Cellar/go@1.16/1.16.13/libexec/src/net/http/server.go:2868\nnet/http.(*conn).serve\n\t/usr/local/Cellar/go@1.16/1.16.13/libexec/src/net/http/server.go:1933"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x654aea]

goroutine 12805 [running]:
net/url.(*URL).String(0x0, 0x36d7a889f25a, 0x2a4b2ed2)
        /usr/local/Cellar/go@1.16/1.16.13/libexec/src/net/url/url.go:813 +0x4a
github.com/fission/fission/pkg/executor/client.(*Client).TapService(0xc0005625a0, 0xc0008e2230, 0xb, 0x0, 0x0, 0xc0008e2249, 0x7, 0x0, 0x0, 0xc0008e40f0, ...)
        pkg/executor/client/client.go:174 +0x45
github.com/fission/fission/pkg/router.(*functionHandler).tapService(...)
        pkg/router/functionHandler.go:461
github.com/fission/fission/pkg/router.functionHandler.collectFunctionMetric(0xc0003e0b40, 0xc000778290, 0xc0005625a0, 0xc000980000, 0xc000e1e3c0, 0xc0009f4210, 0x0, 0x0, 0x0, 0xc000475d70, ...)
        pkg/router/functionHandler.go:816 +0x6b0
created by github.com/fission/fission/pkg/router.functionHandler.getProxyErrorHandler.func1
        pkg/router/functionHandler.go:769 +0x651
```

The trigger's function has this resources load
![image](https://user-images.githubusercontent.com/5422722/154803505-c416655c-486a-4889-9866-1e36e6d6c262.png)

Reproduce the error:
a simple nodejs function with 700 simultaneous request

**Expected result**
router doesn't crash

**Actual result**
router crash and executor rise memory usage up to 100% node ram

Attached dump file
[fission-dump_1645278571.zip](https://github.com/fission/fission/files/8102288/fission-dump_1645278571.zip)

**Comment by virus2016** [comment]
Same

**Comment by sanketsudake** [comment]
Added sanitycheck in tapService to avoid calls https://github.com/fission/fission/pull/2402
