### ISSUE TITLE
fission controller endpoint http://etcd:2379 exceeded header timeout

### ISSUE THREAD

**Issue by ma-sir** [fission/fission#270]
```
kubectl logs -n fission po/controller-2111728440-04gdc


time="2017-08-07T08:32:12Z" level=info msg="Created directory /filestore" 
time="2017-08-07T08:32:12Z" level=info msg="Server started" port=8888 
goroutine 10 [running]:
runtime/debug.Stack(0x0, 0xf8, 0xf8)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/fission/fission/controller.(*API).respondWithError(0xc420206f00, 0x7f9976a34a38, 0xc420320690, 0x202b740, 0xc4201c02a0)
	/Users/soam/gopath/src/github.com/fission/fission/controller/api.go:73 +0x29
github.com/fission/fission/controller.(*API).FunctionApiList(0xc420206f00, 0x7f9976a34a38, 0xc420320690, 0xc4200b8800)
	/Users/soam/gopath/src/github.com/fission/fission/controller/functionApi.go:36 +0x14f
github.com/fission/fission/controller.(*API).FunctionApiList-fm(0x7f9976a34a38, 0xc420320690, 0xc4200b8800)
	/Users/soam/gopath/src/github.com/fission/fission/controller/api.go:105 +0x48
net/http.HandlerFunc.ServeHTTP(0xc4202ff380, 0x7f9976a34a38, 0xc420320690, 0xc4200b8800)
	/usr/local/go/src/net/http/server.go:1942 +0x44
github.com/fission/fission/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4202b5540, 0x7f9976a34a38, 0xc420320690, 0xc4200b8800)
	/Users/soam/gopath/src/github.com/fission/fission/vendor/github.com/gorilla/mux/mux.go:114 +0x10c
github.com/fission/fission/vendor/github.com/gorilla/handlers.loggingHandler.ServeHTTP(0x2030ac0, 0xc42000c018, 0x202bc80, 0xc4202b5540, 0x203da80, 0xc4200c8380, 0xc4200b8500)
	/Users/soam/gopath/src/github.com/fission/fission/vendor/github.com/gorilla/handlers/handlers.go:69 +0x121
github.com/fission/fission/vendor/github.com/gorilla/handlers.(*loggingHandler).ServeHTTP(0xc4201c0020, 0x203da80, 0xc4200c8380, 0xc4200b8500)
	<autogenerated>:8 +0x86
net/http.serverHandler.ServeHTTP(0xc4200862c0, 0x203da80, 0xc4200c8380, 0xc4200b8500)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc42026c000, 0x203ee00, 0xc420278280)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
time="2017-08-07T08:33:19Z" level=error msg="Error: 500: client: etcd cluster is unavailable or misconfigured; error #0: client: endpoint http://etcd:2379 exceeded header timeout
" 
172.17.0.1 - - [07/Aug/2017:08:33:18 +0000] "GET /v1/functions HTTP/1.1" 500 123
```

**Comment by soamvasani** [comment]
we stopped calling etcd directly (we're using TPRs now and soon CRDs).
