### ISSUE TITLE
Error Installing Numpy in Fission Builder Image. 

### ISSUE THREAD

**Issue by prajinkhadka** [fission/fission#2995]
**Fission/Kubernetes version**
client:
  fission/core:
    BuildDate: "2024-07-28T22:58:43Z"
    GitCommit: e0a3e9d3
    Version: v0.0.0
server:
  fission/core:
    BuildDate: "2024-01-14T15:43:35Z"
    GitCommit: 7e8d5dd7
    Version: v1.20.1
 

**Kubernetes platform (e.g. Google Kubernetes Engine)**
Docker Application Mac M1  Air 

**Describe the bug**
I am trying to install a specific version of NumPy using the Fission Builder Docker Image for  Python3.8 but it throws this error. 
The Fission Docker Image that I am using is: 
fission/python-builder-3.8 with x86_64 architecture.

The numpy version I am trying to install is 1.18 which is supported in Python3.8. I tried installing in the Aws Lambda Image (amazon/aws-lambda-python:3.8), it works.

The error log from Fission Builder Image is: 

```
Collecting numpy==1.18
  Downloading numpy-1.18.0.zip (5.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 12.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]

      Error compiling Cython file:
      ------------------------------------------------------------
      ...
          def __init__(self, seed=None):
              BitGenerator.__init__(self, seed)
              self.rng_state.pcg_state = &self.pcg64_random_state

              self._bitgen.state = <void *>&self.rng_state
              self._bitgen.next_uint64 = &pcg64_uint64
                                         ^
      ------------------------------------------------------------

      _pcg64.pyx:113:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to the type of the value being assigned.
      /tmp/pip-install-i0awy8fq/numpy_f5bfa763e3ee4d92a500cb7b0d63a27a/tools/cythonize.py:75: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        required_version = LooseVersion('0.29.13')
      /tmp/pip-install-i0awy8fq/numpy_f5bfa763e3ee4d92a500cb7b0d63a27a/tools/cythonize.py:77: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        if LooseVersion(cython_version) < required_version:
      Processing numpy/random/_bounded_integers.pxd.in
      Processing numpy/random/mtrand.pyx
      Processing numpy/random/_pcg64.pyx
      Traceback (most recent call last):
        File "/tmp/pip-install-i0awy8fq/numpy_f5bfa763e3ee4d92a500cb7b0d63a27a/tools/cythonize.py", line 238, in <module>
          main()
        File "/tmp/pip-install-i0awy8fq/numpy_f5bfa763e3ee4d92a500cb7b0d63a27a/tools/cythonize.py", line 234, in main
          find_process_files(root_dir)
        File "/tmp/pip-install-i0awy8fq/numpy_f5bfa763e3ee4d92a500cb7b0d63a27a/tools/cythonize.py", line 225, in find_process_files
          process(root_dir, fromfile, tofile, function, hash_db)
        File "/tmp/pip-install-i0awy8fq/numpy_f5bfa763e3ee4d92a500cb7b0d63a27a/tools/cythonize.py", line 191, in process
          processor_function(fromfile, tofile)
        File "/tmp/pip-install-i0awy8fq/numpy_f5bfa763e3ee4d92a500cb7b0d63a27a/tools/cythonize.py", line 80, in process_pyx
          subprocess.check_call(
        File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/usr/local/bin/python', '-m', 'cython', '-3', '--fast-fail', '-o', '_pcg64.c', '_pcg64.pyx']' returned non-zero exit status 1.
      Running from numpy source directory.
      <string>:425: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      Cythonizing sources
      Traceback (most recent call last):
        File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-5t4cl1s2/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 373, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-5t4cl1s2/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 502, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-5t4cl1s2/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 450, in <module>
        File "<string>", line 433, in setup_package
        File "<string>", line 240, in generate_cython
      RuntimeError: Running cythonize failed!
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: You are using pip version 22.0.4; however, version 24.2 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
/ #

``` 

**To Reproduce**

docker pull --platform linux/amd64 fission/python-builder-3.8

docker run -it --entrypoint sh fission/python-builder-3.8

pip3 install numpy==1.18 

I tried using a different version of Python, installing Python3-dev, but no success. 
Any suggestions on what I can do here to install this specific version?

**Comment by sanketsudake** [comment]
Please try latest environments from Github packages https://fission.io/environments/
