### ISSUE TITLE
Python environment not working

### ISSUE THREAD

**Issue by prasenforu** [fission/fission#372]
Deployed in Kubernetes 1.8 using kubeadm

Other functions (php, nodejs) working as per example but python not working getting following error in poolmgr pod's log.

```
2017/10/10 02:57:22 [hello_world] Checking for cached function service
2017/10/10 02:57:22 [hello_world] No cached function service found, creating one
2017/10/10 02:57:22 [hello_world] getting environment for function
2017/10/10 02:57:22 [&{hello_world f6c6faac-e9d3-411d-b746-d3edbe6725b5}] getting function from controller
2017/10/10 02:57:22 [&{hello_world f6c6faac-e9d3-411d-b746-d3edbe6725b5}] getting env from controller
2017/10/10 02:57:22 [hello_world] getting generic pool for env
2017/10/10 02:57:22 [hello_world] getting function service from pool
2017/10/10 02:57:22 [&{hello_world f6c6faac-e9d3-411d-b746-d3edbe6725b5}] Choosing pod from pool
2017/10/10 02:57:22 [map[poolmgrInstanceId:QvVDKWnN unmanaged:true functionName:hello_world functionUid:f6c6faac-e9d3-411d-b746-d3edbe6725b5]] found 3 ready pods of 3 total
2017/10/10 02:57:22 relabeling pod: [python-60ea1ceb-df20-4323-ad36-d434300ff169-imj7jihf-5c4b7bk7tq]
2017/10/10 02:57:22 Chosen pod: python-60ea1ceb-df20-4323-ad36-d434300ff169-imj7jihf-5c4b7bk7tq (in 10.50162ms)
2017/10/10 02:57:22 [&{hello_world f6c6faac-e9d3-411d-b746-d3edbe6725b5}] calling fetcher to copy function
2017/10/10 02:57:22 [&{hello_world f6c6faac-e9d3-411d-b746-d3edbe6725b5}] specializing pod
2017/10/10 02:57:22 Error connecting to ip-172-31-16-61 log daemonset pod: Post http://172.31.16.61:1234/v1/log: dial tcp 172.31.16.61:1234: getsockopt: connection refused
2017/10/10 02:57:22 Failed to specialize pod: Internal error - <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
2017/10/10 02:57:22 Error: 500: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
2017/10/10 02:57:22 Error in pod 'python-60ea1ceb-df20-4323-ad36-d434300ff169-imj7jihf-5c4b7bk7tq', scheduling cleanup
10.244.1.5 - - [10/Oct/2017:02:57:22 +0000] "POST /v1/getServiceForFunction HTTP/1.1" 500 291
```

cat hello_world.py
```
def main():
    return “Hello, World!\n”
```

looks like issue was in python env.

**Comment by prasenforu** [comment]
@vishal-biyani  Thanks Vishal.

No difference between two code, apart from double cote in my case & you used single cote.

But its interesting, tomorrow we will try and update you.

**Comment by soamvasani** [comment]
@prasenforu do you have the logs from the function itself? You can get them with: `kubectl -n fission-function get pod -l functionName=hello_world` and then `kubectl -n fission-function logs <that pod>`

**Comment by prasenforu** [comment]
Now its taking both double & single cote. not sure why it was throwing error.

Anyway its normal testing, but I am doing some real life testing ...

##### Below code which will list all the Instances and associated IP Address in AWS.

```
import boto
from boto import ec2
connection=ec2.connect_to_region('ap-southeast-2',aws_access_key_id='XXXXXXXX',aws_secret_access_key='YYYYYYYYYY')
reservations=connection.get_all_instances();
 
for reservation in reservations:
 for instances in reservation.instances:
 print "%s \t \t %s" % (instances.tags['Name'], instances.ip_address) 
```

Above is working fine from any linux host but as a function its not working, throwing error as follows.

```
Internal server error (fission)
```

When I am checking in Fission function pod its saying as follows ..

```
2017-10-11 07:15:05,594 - INFO - Starting server
 * Running on http://0.0.0.0:8888/ (Press CTRL+C to quit)
2017-10-11 07:19:35,592 - ERROR - Exception on /specialize [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 19, in load
    userfunc = (imp.load_source('user', codepath)).main
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/userfunc/user", line 5
    reservations=connection.get_all_instances();
```

**Comment by vishal-biyani** [comment]
Closing for lack of activity.
