### ISSUE TITLE
Function logs CI setup issue

### ISSUE THREAD

**Issue by vishal-biyani** [fission/fission#653]
This commands in sequence work fine from local machine pointing to a GKE Fission setup, but fail in the CI setup every time.
```
$ fission env create --name node --image fission/node-env
$ fission fn create --name hello --env node --code badhello.js 
$ fission fn test --name hello
Error calling function hello: 502 
> fission-nodejs-runtime@0.1.0 start /usr/src/app
> node server.js

Codepath defaulting to  /userfunc/user
Port defaulting to 8888
user code load error: SyntaxError: Unexpected token function
::ffff:10.8.4.17 - - [29/Apr/2018:03:40:34 +0000] "POST /specialize HTTP/1.1" 500 2 "-" "Go-http-client/1.1"

```

The error in CI is:

```
goroutine 2609 [running]:
runtime/debug.Stack(0xc4202cf390, 0x10, 0x10)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/debug/stack.go:16 +0x22
github.com/fission/fission/controller.(*API).respondWithError(0xc4203d0900, 0x7f231f491a38, 0xc420704ff0, 0x20fe6a0, 0xc4202cf390)
	src/github.com/fission/fission/controller/api.go:98 +0x29
github.com/fission/fission/controller.(*API).FunctionPodLogs(0xc4203d0900, 0x7f231f491a38, 0xc420704ff0, 0xc420210d00)
	src/github.com/fission/fission/controller/functionApi.go:241 +0x71b
github.com/fission/fission/controller.(*API).FunctionPodLogs-fm(0x7f231f491a38, 0xc420704ff0, 0xc420210d00)
	src/github.com/fission/fission/controller/api.go:196 +0x48
net/http.HandlerFunc.ServeHTTP(0xc4202ce5b0, 0x7f231f491a38, 0xc420704ff0, 0xc420210d00)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/http/server.go:1942 +0x44
github.com/fission/fission/vendor/github.com/gorilla/handlers.loggingHandler.ServeHTTP(0x2105060, 0xc42000c018, 0x2106d20, 0xc4202ce5b0, 0x2114da0, 0xc4202b1dc0, 0xc420210d00)
	src/github.com/fission/fission/vendor/github.com/gorilla/handlers/handlers.go:69 +0x121
github.com/fission/fission/vendor/github.com/gorilla/handlers.(*loggingHandler).ServeHTTP(0xc4203f09a0, 0x2114da0, 0xc4202b1dc0, 0xc420210d00)
	<autogenerated>:8 +0x86
github.com/fission/fission.LoggingMiddleware.func1(0x2114da0, 0xc4202b1dc0, 0xc420210d00)
	src/github.com/fission/fission/common.go:67 +0x10f
net/http.HandlerFunc.ServeHTTP(0xc4203f0940, 0x2114da0, 0xc4202b1dc0, 0xc420210d00)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/http/server.go:1942 +0x44
github.com/fission/fission/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420150460, 0x2114da0, 0xc4202b1dc0, 0xc420210d00)
	src/github.com/fission/fission/vendor/github.com/gorilla/mux/mux.go:159 +0x101
net/http.serverHandler.ServeHTTP(0xc420474210, 0x2114da0, 0xc4202b1dc0, 0xc420210b00)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc42030b680, 0x2116060, 0xc4203df540)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/net/http/server.go:2668 +0x2ce
time="2018-04-28T18:08:37Z" level=error msg="Error: 500: No active pods found" 
10.128.0.9 - - [28/Apr/2018:18:08:37 +0000] "POST /proxy/logs/errhello-487336804 HTTP/1.1" 500 21
10.128.0.8 - - [28/Apr/2018:18:08:37 +0000] "GET /v2/functions/errhello-487336804?namespace=default HTTP/1.1" 200 628
10.128.0.8 - - [28/Apr/2018:18:08:37 +0000] "POST /proxy/influxdb?db=fissionFunctionLog&params=%7B%22funcuid%22%3A%222a57bc21-4b0f-11e8-a656-42010a80010f%22%2C%22time%22%3A0%7D&q=select+%2A+from+%22log%22+where+%22funcuid%22+%3D+%24funcuid+AND+%22time%22+%3E+%24time+LIMIT+1000 HTTP/1.1" 200 46
10.128.0.3 - - [28/Apr/2018:18:08:37 +0000] "DELETE /v2/environments/nodejs-485764527?namespace=default HTTP/1.1" 200 0
10.128.0.2 - - [28/Apr/2018:18:08:37 +0000] "DELETE /v2/functions/hello-486548157?namespace=default HTTP/1.1" 200 0
10.52.3.1 - - [28/Apr/2018:18:08:38 +0000] "DELETE /v2/functions/errhello-487336804?namespace=default HTTP/1.1" 200 0
```
Deatailed log can be found here: https://api.travis-ci.org/v3/job/372596360/log.txt

It is not clear why the CI setup is not able to pickup logs.

**Comment by vishal-biyani** [comment]
Solved by #651, closing for now.
