### ISSUE TITLE
Specific dependencies cause Java function to fail

### ISSUE THREAD

**Issue by vishal-biyani** [fission/fission#841]
After adding specific dependencies in Hello World example of JVM environment, function fail. Even after adding the dependency being complained about, the issue continues.

Dependencies added:
```
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.2.3</version>
        </dependency>
```

`fission fn test` fails with 502 and logs of pod shows:

```
[2018-08-02 17:29:56.990735282 +0000 UTC] 2018-08-02 17:29:56.988 ERROR 1 --- [nio-8888-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: groovy/lang/GroovyObject] with root cause
[2018-08-02 17:29:56.990781683 +0000 UTC] 
[2018-08-02 17:29:56.990786517 +0000 UTC] java.lang.ClassNotFoundException: groovy.lang.GroovyObject
[2018-08-02 17:29:56.990789394 +0000 UTC] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_171]
[2018-08-02 17:29:56.990792495 +0000 UTC] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_171]
[2018-08-02 17:29:56.990798163 +0000 UTC] 	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93) ~[app.jar:0.0.1-SNAPSHOT]
[2018-08-02 17:29:56.990800962 +0000 UTC] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_171]
[2018-08-02 17:29:56.990803477 +0000 UTC] 	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_171]
[2018-08-02 17:29:56.990806007 +0000 UTC] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[na:1.8.0_171]
[2018-08-02 17:29:56.990808553 +0000 UTC] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.8.0_171]
[2018-08-02 17:29:56.990811159 +0000 UTC] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[na:1.8.0_171]
[2018-08-02 17:29:56.990813688 +0000 UTC] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[na:1.8.0_171]
[2018-08-02 17:29:56.990816236 +0000 UTC] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[na:1.8.0_171]
[2018-08-02 17:29:56.990818783 +0000 UTC] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[na:1.8.0_171]
[2018-08-02 17:29:56.990821301 +0000 UTC] 	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_171]
[2018-08-02 17:29:56.990839643 +0000 UTC] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[na:1.8.0_171]
[2018-08-02 17:29:56.990843395 +0000 UTC] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_171]
[2018-08-02 17:29:56.990846006 +0000 UTC] 	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93) ~[app.jar:0.0.1-SNAPSHOT]
[2018-08-02 17:29:56.990848713 +0000 UTC] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:411) ~[na:1.8.0_171]
[2018-08-02 17:29:56.990851228 +0000 UTC] 	at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:814) ~[na:1.8.0_171]
[2018-08-02 17:29:56.990853759 +0000 UTC] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_171]
[2018-08-02 17:29:56.990864224 +0000 UTC] 	at io.fission.Server.specialize(Server.java:84) ~[classes!/:0.0.1-SNAPSHOT]
```

**Comment by vishal-biyani** [comment]
Similarly the dependency:

```
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
            <version>1.2.3</version>
        </dependency>	
```

Causes:

```
java-e09201f9-9563-11e8-9188-42010aa00fcc-scovoboy-67bcc64b6sqd java java.lang.ClassNotFoundException: javax.mail.Authenticator
```

**Comment by ganesh080780** [comment]
@vishal-biyani : it works fine after removing the dependency.

**Comment by vishal-biyani** [comment]
Afte running `mvn dependency:tree -Dverbose` it is clear that Spring Boot ships spring-boot-starter-logging which internally uses logback as documented here (https://docs.spring.io/spring-boot/docs/current/reference/html/howto-logging.html) So one can use all logback configuration and need not add dependency explicitly. Since we dynamically load classes, duplicate dependencies cause issues (For which a separate issue to be raised to investigate). But for now removing `logback-core` & `logback-classic` should make it work.
